import { defineConfig, devices } from '@playwright/test';

/*
	Screenshot baselines are byte-compared, and font rasterisation differs between
	macOS and Linux — the same page produces a different PNG on each. So the
	baselines in this repo are Linux-only, generated by the
	`visual-baselines` workflow, and `tests/visual.spec.ts` refuses to write them
	anywhere else. The path template deliberately omits the platform token so a
	macOS run cannot quietly create a second, parallel set.
*/
export default defineConfig({
	testDir: 'tests',
	snapshotPathTemplate: '{testDir}/__screenshots__/{arg}{ext}',
	/*
		Playwright's default is `updateSnapshots: 'missing'`, which WRITES a missing
		baseline during an ordinary run and reports a pass. On macOS that silently
		produced eight baselines CI could never match — found by watching this
		suite go green when it had nothing to compare against. A missing baseline
		is a failure here; only the Linux workflow may create one, and it passes
		`--update-snapshots` explicitly.
	*/
	updateSnapshots: 'none',
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: 0,
	workers: process.env.CI ? 2 : undefined,
	reporter: process.env.CI ? [['github'], ['html', { open: 'never' }]] : [['list']],
	expect: {
		toHaveScreenshot: {
			// Anti-aliasing moves a handful of pixels between otherwise identical
			// runs. Anything that actually changed a component moves far more.
			maxDiffPixelRatio: 0.01,
			animations: 'disabled',
			caret: 'hide',
			scale: 'css'
		}
	},
	use: {
		baseURL: `http://localhost:${process.env.PORT ?? 4173}`,
		colorScheme: 'light',
		deviceScaleFactor: 1,
		...devices['Desktop Chrome']
	},
	webServer: {
		command: 'node scripts/serve-static.mjs',
		url: `http://localhost:${process.env.PORT ?? 4173}/`,
		reuseExistingServer: !process.env.CI,
		timeout: 60_000
	}
});
