export const ROUTES = {
  HOME: '/',
  DOCS: '/docs',
  COMPONENTS: '/components',
}

export const COMPONENTS_ROUTES = {
  BUTTON: '/components/button',
  INPUT: '/components/input',
  MODAL: '/components/modal',
  TOAST: '/components/toast',
  TOOLTIP: '/components/tooltip',
  SPINNER: '/components/spinner',
  SWITCH: '/components/switch',
  RADIO: '/components/radio',
  CHECKBOX: '/components/checkbox',
  SELECT: '/components/select',
  TEXTAREA: '/components/textarea',
  NAVIGATION: '/components/navigation',
  TABLE: '/components/table',
  PAGINATION: '/components/pagination',
  DATEPICKER: '/components/datepicker',
  TIMEPICKER: '/components/timepicker',
  DIALOG: '/components/dialog',
  SNACKBAR: '/components/snackbar',
  PROGRESS: '/components/progress',
  SLIDER: '/components/slider',
  BREADCRUMB: '/components/breadcrumb',
  STEPPER: '/components/stepper',
  ACCORDION: '/components/accordion',
  TABS: '/components/tabs',
  TOGGLE: '/components/toggle',
  MENU: '/components/menu',
  POPUP: '/components/popup',
  CHIPS: '/components/chips',
  FILE: '/components/file',
  UPLOAD: '/components/upload',
  IMAGE: '/components/image',
  AVATAR: '/components/avatar',
  BADGE: '/components/badge',
  LIST: '/components/list',
  CARD: '/components/card',
  CAROUSEL: '/components/carousel',
  EXPANDABLE: '/components/expandable',
  GRID: '/components/grid',
  STACK: '/components/stack',
  TYPOGRAPHY: '/components/typography',
  ICON: '/components/icon',
  AVATAR_GROUP: '/components/avatar-group',
  BANNER: '/components/banner',
  DRAWER: '/components/drawer',
  FAB: '/components/fab',
  FORM: '/components/form',
  MENU_BUTTON: '/components/menu-button',
  MENU_ITEM: '/components/menu-item',
  MENU_LIST: '/components/menu-list',
  MENU_DIVIDER: '/components/menu-divider',
  MENU_HEADER: '/components/menu-header',
  MENU_ITEM_GROUP: '/components/menu-item-group',
  MENU_SUBMENU: '/components/menu-submenu',
  MENU_ITEM_ICON: '/components/menu-item-icon',
  MENU_ITEM_TEXT: '/components/menu-item-text',
  MENU_ITEM_ACCELERATOR: '/components/menu-item-accelerator'
}

export const MOBILE_WIDTH_THRESHOLD = 1024;
